module.exports = [
  {
    text: `If anyone tries to hit on me, flirt with me, message or text me, I will tell them that I am in the most loving relationship I have ever been in, and have an amazing boyfriend who I dearly love. I love you so much! You are seriously my best friend! My rock! The sun to my cloudy day! My one true love! I don't know what I would do without you! I've been blessed with the best! The little things you say to me always put a smile on my face. You make me want to listen to love songs, you still give me butterflies, and you still make me speechless. I don't know how I got so lucky to have such an amazing person like you in my life. You're the best boyfriend anyone could have asked for. I am truly blessed. I love you to infinity and beyond. I just wanted to do something simple to say you're amazing and to put that smile I love so much on your face. I want everyone to know how much you mean to me. Ever since you have entered my life, I've been flying on Cloud 9 and I have not come down yet. I still don't know what I did to be so lucky to have you in my life, my dream come true! I want to spend every second of my life with you. You give me everything I want in a man. It brings me happiness every day that a handsome man like you is my husband. I just want you to know that I love you!`
  },
  {
    text: `There are times in my life where I feel lost. It's hard to explain but it's almost like I'm untethered from something that used to keep me grounded, like a kite that's lost in the wind. But then I come home, I see you, you ask me how my day went or start talking about your day and what's happened to you, and it's like you're bringing me back to myself. I can feel myself settle back into my own skin. You ground me and bring me a sense of security and safety I've never known before. I have so much confidence in us and in our love, in the way, I feel about you and the way you feel about me. You know I love you so much and it gives me such strength. I wanted you to know how much you mean to me, what you do for me. Without you, I'm so lost but with you, I'm found again. Those kisses you gave me have been a trace of sweetness in my heart. Anytime I miss you, I find a reason to recall that day we were together under the tree. I feel like holding you right now so I can feel the warmth of your body. I love you!`
  },
  {
    text: `I want you to know that you are the most important thing in my life. You're the reason I do everything. When I get up in the morning, I feel so grateful for every second I have with you and have here on earth. You give my life meaning, you give my days such joy, you are the reason I smile. Thank you for being with me, for joining me on this journey through life. Your love is everything to me. You make me feel beautiful. Thank you for giving me so much more than I ever could have wanted. I am so thankful for what we have, and for everything, we will have. You are the only man I ever want to share my life with. I could never imagine what it would be like if we were to lose each other. I don't even want to think about it. All I want to think about is you. You are the love of my life. I love you. I always will love you until the day that I die. Hopefully, when that day comes, I will still have you by my side and you face will be the last face that I see.`
  },
  {
    text: `Darling, I was trying to go to sleep last night but I couldn't. I just kept looking out the window at the moon, wondering what you were thinking about, or dreaming about. I'm sorry about our fight. I know we're going to work through this and that we're going to be stronger because of it. You are such an amazing partner. I feel like I can tell you anything and I know you'll never judge me for anything at all. Relationships can be hard sometimes, especially between us because we're both such stubborn people. But even though we have our differences, I believe in us and believe that we can make this work. So I hope that right now, as you're reading this message, you know that I love you and that I can't wait until I see you again. You are hilarious! Even when we argue, you make it funny and just crazy! I love your sense of humor and randomness. I think you've kind of spoiled me actually. Ever since we started chatting, everyone else is just so boring.`
  },
  {
    text: `People ask me how we can stay in this long-distance relationship for so long and I just smile. If they knew you, they wouldn't ask. If they knew how amazing you are, how thoughtful, how funny, how kind, how handsome, how generous, how forgiving, how wonderful, how silly, how serious, how deep, how affectionate, how playful, how brilliant, how creative, how indescribable you are,they wouldn't ask. I would be a fool to ever give up what we have. I would be a fool to think I could find someone like you anywhere else. You are the only you. And you are the only you for me. I am so happy that we're together, even though the distance can get hard. It is so worth it. One day, we'll be together, in the same place, and I'll get to see your sweet smile and hold your beautiful face. Until then, I hope you know that I love you. I love you so much. My life won't be complete without you in it. I knew I was in paradise when I slept and woke up with you by my side. My love for you is thick because I have not felt this way for anyone. I will always love you because my feelings for you will stay till eternity. I have never felt this hollow in my life before. The thought of not seeing you for another day can be heartbreaking. Can I stay in your heart to stop this nuclear explosion? The heart knows what it desires, but I know that yours yearn for the warm feelings we share all day long.`
  },
  {
    text: `Hey baby, I was just thinking about you while I was on my way to work. You make me smile all the time, even when we're not together. I just picture your face and your big bright eyes, and I can't help it. I'm so lucky I am to be with you. How lucky we are that we met each other. I feel like there are so many signs in my life that show we are meant to be together. There are so many things about you that I love. I couldn't name them all even if I tried. Each day that I get to know you, I learn more about how wonderful you are. I brag about you all the time to my friends and family, and even though they might get sick of hearing about you, I never get sick of talking about you. Getting married is all I can think about. I hope you have a good night and that you sleep well. Watching you walk across a room is the greatest gift. The way you move is so strong and sure. The way you smile makes me feel at peace. Knowing you're walking towards me is a feeling so hard to describe. It's like coming home, a comfort, only the home is coming to me. I will never know such love, such peace, as you. You're my home.`
  },
  {
    text: `It's amazing the love and care you give me on a daily basis it's unequaled I think I am safer with you, that's why I am giving all myself to you, because my life is perfect with you, and I promise to love you and give you all you need, may God bless you continually for me, because you really deserve much more than I can give you. I love you so much. You are such a gift to me. Having you in my life is such a blessing. Every day, I thank God that you are in my life and that you are by my side. I am so blessed to be able to call you mine and to be called yours. I pray that I will always be able to give you what you need in life and that you will always be there to hold my hand and that you will continue to walk with me on this journey that we call life. Before I met you, all my relationships always seemed so hard.  They were something I had to work at and it felt forced. With you everything is so easy. Loving you comes so naturally, and it has from the very beginning. It's as if I looked up and there you were: This amazing man. And then there it was: This amazing love I have for you. It's been the greatest surprise of my life. When we're together, I feel as though I'm invincible. It's like every piece of me is so weightless that I can drift from one cloud to another without ever coming down. I never want this feeling to end.`
  },
  {
    text: `When you feel weak, I am here to be strong for you. When you are strong, I'm here to lift you up and make you stronger. And, when you are sad, I am here to bring a smile to your face. And when you are happy, I am here to enjoy every minute of it. Because you do all these things for me. When I am weak, you give me strength. When I am sad, you make me smile. I am so grateful for you and our life together. I have found my perfect partner. When I was a kid I used to sit and think of what the person I loved would be like. I pictured kissing in fields or maybe on the beach. A man who was strong and kind. Who was smart and driven. Who made me laugh. And, who made me stronger. You are so much more than I could have ever imagined. I never even thought to wish for someone as kind, sweet, strong, funny, smart, and amazing as you. You are life's biggest surprise. You are so much more than anything I could have dreamed or hoped for. I know I say “I love you” all the time, but that's not enough. Those three words can't describe the way I feel about you. You make my tummy do flips and my hands shake. I've never loved anyone as much as I love you and I don't think I will ever love someone this much again. You're everything I have ever wanted and needed. I love you so much! You're my everything, my entire heart, and world.`
  },
  {
    text: `There are moments when we're together, where I wish I could make time stop. I often think to myself, that I could easily stay in this moment forever. Just being with you, sitting with you, touching your cheek, or stroking your back. Feeling you by my side is everything to me. Every moment I spend with you is the best moment of my life. I love you, and I will go on loving you through all the moments we share together from now until forever. I can say it a million times and it still won't be enough: I love you. Your love is amazing. It's perfect. It's great. I've seen love before, but not like this. This love is exceptional. Thank you for being my partner.
        Sometimes I try to think of what my life would be like without you. What I would be like or what I'd do with my days. It's so hard because so much of who I am now is due to you. You've challenged me, inspired me, encouraged me, and supported me. And it's because of all this that I'm the person I am today. I am so grateful for your presence in my life and for the love and attention to give to me, our relationship, and our life together. I couldn't ask for anything more. And, I love you so much. The bliss my soul enjoys each time I see your face can brighten the darkest planet. I love you plenty. Your love is engulfing, and the feeling is enticing. Your assurance is comforting, and my heart is in the safest place on earth. I love you.`
  },
  {
    text: `A million stars up in the sky one shines brighter I can't deny. A love so precious a love so true a love that comes from me to you, The angels sing when you are near within your arms I have nothing to fear You always know just what to say just talking to you makes my day. I love you honey with all of my heart together forever and never to part. I know that when I am older, I will look back at the days when we used to argue about petty things and I will be happy, knowing that our love was stronger and bigger than those things. You need to know that I am thankful that you are in my life and that I will love you till the day I die. Unconditionally and without any end, I love you, baby! You know you've completely changed my life, in every way inside and out. When everything wasn't in my favor you stepped in and made everything better for me and unconditionally changed myself with lots of positivity. I love you so much and if any day I have to sacrifice my life for you than I possibly do. You make my heart beat faster than ever. I love the way how you take care of me. Those make my day and all your activity makes my heart just melts to love with you.`
  }
]
